# Generated by Django 3.0.7 on 2020-06-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='project/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='project/')),
                ('description', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=100)),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
